pipeline {
    agent any

    stages {
        stage('Download files from GitHub') {
            steps {
                git branch: 'terraform', url: 'https://github.com/b-c-v/CI-CD-Project.git'
            }
        }
        stage('Terraform initialize') {
            steps {
                sh 'cd $WORKSPACE/1_environment/Terraform/ && terraform init'
            }
        }
        stage('Terraform apply') {
            steps {
                withCredentials([aws(credentialsId: 'cicd-credentials', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh 'cd $WORKSPACE/1_environment/Terraform/ && terraform apply --auto-approve'
                }
            }
        }

        stage('Ansible') {
            steps {
                ansiColor('xterm') {
                    ansiblePlaybook colorized: true, disableHostKeyChecking: true, installation: 'ansible', inventory: '/cicd/inventory.ini', playbook: '$WORKSPACE/1_environment/Ansible/playbook.yml'
                }
            }
        }
    }
}
