apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-project
  labels:
    app: cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd

  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: cicd
          image: dqqm/tomcatcicd
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
