- name: Configure EC2 for Jenkins
  hosts: public_0
  become: yes

  tasks:
    - name: Change hostname
      shell: hostnamectl set-hostname jenkins

    - name: Update server
      shell: yum update -y

    - name: install Jenkins
      shell: |
        yum update –y
        wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
        rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        yum upgrade
        amazon-linux-extras install java-openjdk11 -y
        yum install jenkins -y
        systemctl enable jenkins
        systemctl start jenkins
    - command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password

    - name: print password to Jenkins
      debug: msg={{ jenkins_password.stdout }}

    - name: Install Git
      package:
        name: git
        state: present

    - name: Install Maven
      package:
        name: maven
        state: present

- name: Configure EC2 for Docker
  hosts: public_1
  become: yes
  vars:
    username: dockercicd
    password: !test123

  tasks:
    - name: Change hostname
      shell: hostnamectl set-hostname docker
    - name: Update server
      shell: yum update -y
    - name: install Docker
      package:
        name: docker
        state: present
    - name: Enable Docker service at boot time
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add new user
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        state: present
        update_password: on_create
      register: "{{ username }}"

    - name: Add user to docker group
      user:
        name: "{{ username }}"
        groups: docker
        append: yes

    - name: Create directory for project
      file:
        path: "/opt/docker"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Change SSH configuration
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication no"
        line: "PasswordAuthentication yes"
        notify: restart ssh

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted

- name: Configure EC2 for Ansible
  hosts: public_2
  become: yes

  tasks:
    - name: Change hostname
      shell: hostnamectl set-hostname ansible
    - name: Update server
      shell: yum update -y
    - name: Install Ansible
      shell: amazon-linux-extras install ansible2 -y

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
