- name: ==== 1. Configure EC2 for Jenkins ====
  hosts: public_0
  become: true

  tasks:
    - name: Wait when instance will be ready
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 5
        timeout: 300
        state: started

    - name: Change hostname
      shell: hostnamectl set-hostname jenkins

    - name: yum update
      yum:
        name: "*"
        state: latest

    - name: Add the jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import a key file from jenkins-ci
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: yum update
      yum:
        name: "*"
        state: latest

    - name: Install Java
      shell: amazon-linux-extras install java-openjdk11 -y

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Start Jenkins
      ansible.builtin.systemd:
        enabled: yes
        name: jenkins
        state: started

    - name: Save Jenkins login password to variable
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
    - name: Your Jenkins login password
      debug: msg={{ jenkins_password.stdout }}

    - name: Install Jenkins plugins
      community.general.jenkins_plugin:
        name: "{{ item }}"
        url_username: "admin"
        url_password: "{{ jenkins_password.stdout }}"
        url: http://localhost:8080
        timeout: 90
      with_items:
        - git
        - github
        - maven-plugin
        - deploy
        - publish-over-ssh
    - name: Restart Jenkins to make the plugin data available
      service:
        name: jenkins
        state: restarted

    - name: Install Git
      package:
        name: git
        state: present

    - name: Install Maven
      package:
        name: maven
        state: present

- name: ==== 2. Configure EC2 for Docker ====
  hosts: public_1
  become: true
  vars:
    docker_username: dockercicd
    ansible_username: ansiblecicd
    password: cicd1234!

  tasks:
    - name: Change hostname
      shell: hostnamectl set-hostname docker
    - name: Update server
      shell: yum update -y

    - name: Install Docker
      package:
        name: docker
        state: present
    - name: Enable Docker service at boot time
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add Docker and Ansible users to system
      user:
        name: "{{ item.username }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present
        update_password: on_create
      loop:
        - { username: "{{ docker_username }}" }
        - { username: "{{ ansible_username }}" }

        # CONFIGURATION FOR ANSIBLE USER

    - name: Solve error Got permission denied while trying to connect to the Docker daemon socket
      command: chmod 777 /var/run/docker.sock

    - name: Allow ansible user run command with sudo
      lineinfile:
        path: /etc/sudoers
        insertafter: "^(.*)## Allows people in group wheel to run all commands(.*)$"
        line: "{{ ansible_username }}  ALL=(ALL) ALL"

        # CONFIGURATION FOR DOCKER USER

    - name: Create directory for project
      file:
        path: "/opt/docker"
        state: directory
        owner: "{{ docker_username }}"
        group: "{{ docker_username }}"

    - name: Add Docker user to docker group
      user:
        name: "{{ docker_username }}"
        groups: docker
        append: yes

    - name: Change SSH configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^(.*)PasswordAuthentication no(.*)$"
        line: "PasswordAuthentication yes"
      notify: Restart ssh
  handlers:
    - name: Restart ssh
      shell: service sshd restart

- name: ==== 3. Configure EC2 for Ansible ====
  hosts: public_2
  become: true
  vars:
    username: ansiblecicd
    password: cicd1234!

  tasks:
    - name: Change hostname
      shell: hostnamectl set-hostname ansible
    - name: Update server
      shell: yum update -y
    - name: Install Ansible
      shell: amazon-linux-extras install ansible2 -y

    - name: Install Docker
      package:
        name: docker
        state: present
    - name: Enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add new user
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present
        update_password: on_create
    - name: Add user to docker group
      user:
        name: "{{ username }}"
        groups: docker
        append: yes

    - name: Create directory for project
      file:
        path: "/opt/docker"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Copy inventory file to project directory
      ansible.builtin.copy:
        src: /tmp/inventory.ini
        dest: /opt/docker/inventory.ini
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0644"

    - name: Solve error Got permission denied while trying to connect to the Docker daemon socket
      command: chmod 777 /var/run/docker.sock

    - name: Allow ansible user run command with sudo
      lineinfile:
        path: /etc/sudoers
        insertafter: "^(.*)## Allows people in group wheel to run all commands(.*)$"
        line: "{{ username }}  ALL=(ALL) ALL"

    - name: Generate SSH key
      become_user: "{{ username }}"
      shell: ssh-keygen -q -b 2048 -t rsa -N "" -P "" -f ~/.ssh/id_rsa

    - name: Change SSH configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^(.*)PasswordAuthentication no(.*)$"
        line: "PasswordAuthentication yes"
      notify: Restart ssh
  handlers:
    - name: Restart ssh
      shell: service sshd restart
