---
- name: Run Docker container with Java app on Tomcat server
  hosts: docker

  tasks:
    - name: stop existing container
      command: docker container stop tomcatcicd
      ignore_errors: yes

    - name: remove existing container
      command: docker container rm tomcatcicd
      ignore_errors: yes

    - name: remove existing image
      command: docker image rm dqqm/tomcatcicd:latest

    - name: run Docker container on remote server
      command: docker container run -d --name tomcatcicd -p 8519:8080 dqqm/tomcatcicd:latest
